```{r}
data <- list()
data$fred <- data$port <- data$census_bps <- list()
```

```{r, data_fred}

# This product uses the FRED® API but is not endorsed or certified by the Federal Reserve Bank of St. Louis.

fredr_set_key(fredr_get_key())
```

```{r}

if (
  # if xlsx file is NOT in the inputs folder OR...
  !file.exists("inputs/data_census_bps.txt") |
  # if port data was last modified last month (or before that)...
  month(file.mtime("inputs/data_census_bps.txt")) < month(today())) {
  # ... fetch new data
  
  download.file(
    "https://www2.census.gov/econ/bps/Place/West%20Region/we2202y.txt", 
    destfile = "inputs/data_census_bps.txt", mode = "wb")
}

# colnames are across two rows in this dataset
data$census_bps <- read.delim(
  "inputs/data_census_bps.txt", sep = ",", header = FALSE, row.names = NULL) 

colnames(data$census_bps) <- paste(data$census_bps[1, ], data$census_bps[2, ])

data$census_bps <- data$census_bps %>%
  pivot_longer(cols = -(`Survey Date`:`Place Name`)) %>%
  filter(`Place Name` == "Portland") %>%
  mutate(
    name = str_trim(name),
    # Cols are missing names under original data structure; this pulls the # of units
    # across all column names
    name = case_when(
      name == "Value" ~ paste(lag(gsub(" Units", "", name), 1), name),
      name == "Bldgs" ~ paste(lead(gsub(" Units", "", name), 1), name),
      TRUE ~ name))
```


```{r, data_port_air}
if (
  # if xlsx file is NOT in the inputs folder OR...
  !file.exists("inputs/data_port_air.xlsx") |
  # if port data was last modified last month (or before that)...
  month(file.mtime("inputs/data_port_air.xlsx")) < month(today())) {
  # ... fetch new data
  
  download.file(
    paste0(
    "https://cdn.portofportland.com/pdfs/",
    month(params$end_date, label = TRUE, abbr = FALSE),
    "%20",
    year(params$end_date),
    "%20Statistics%20(Excel).xlsx"), 
    destfile = "inputs/data_port_air.xlsx", mode = "wb")
  
  data$port$passenger <- read_xlsx(
    "inputs/data_port_air.xlsx", sheet = "Passenger Traffic Report",
    skip = 5)
  
  data$port <- data$port %>%
    map(filter, Carrier %in% c("PDX Total", "PDX Total *")) %>%
    map(select, 2) # keep that month's column only
  
  names(data$port$passenger) <- "Passengers"
  
data$port$passenger_historical <- readRDS("inputs/data_port_passenger_historical.rds")
  
  data$port$passenger_historical <-
    bind_rows(data$port$passenger_historical,
              tibble(Month = floor_date(params$end_date, unit = "month"),
                     Passengers = as.numeric(data$port$passenger))) %>%
    arrange(Month)
   data$port$passenger_historical %>%
    arrange(Month) %>%
     
  saveRDS(data$port$passenger_historical, "inputs/data_port_passenger_historical.rds")

}

data$port$passenger_historical <- readRDS("inputs/data_port_passenger_historical.rds")



```

```{r, data_port_marine}
if (
  # if xlsx file is NOT in the inputs folder OR...
  !file.exists("inputs/data_port_marine.pdf") |
  # if port data was last modified last month (or before that)...
  month(file.mtime("inputs/data_port_marine.pdf")) < month(today())) {
  # ... fetch new data
  
  download.file(
    paste0("https://cdn.portofportland.com/pdfs/ExecDirReport",
           year(params$end_date), month(params$end_date, label = TRUE), ".pdf"), 
    destfile = "inputs/data_port_marine.pdf", mode = "wb")
}

data$port$marine <- pdf_text("inputs/data_port_marine.pdf")[1] %>%
  strsplit("\n") %>%
  unlist() %>%
  tibble() %>%
  set_names("Marine Freight") %>%
  filter(row_number() > grep("UNIT OF MEASURE: METRIC TONS", `Marine Freight`)) %>%
  separate(`Marine Freight`,
           into = c("Month", (year(params$end_date) - 4):year(params$end_date)),
           sep = "\\s+")%>%
  filter(Month %in% toupper(month(1:12, label = TRUE, abbr = FALSE))) %>%
  pivot_longer(as.character((year(params$end_date) - 4):year(params$end_date)),
               names_to = "Year", values_to = "Total Tonnage") %>%
  mutate(Date = mdy(paste(Month, "1", Year)),
         `Total Tonnage` = as.numeric(gsub(",", "", `Total Tonnage`))) %>%
  select(-Month, -Year) %>%
  arrange(Date) %>%
  relocate(Date) %>%
  filter(!is.na(`Total Tonnage`))
```