Economy
=====================================  

```{r}
h3("Total Employment, Portland MSA")
```

Row
-------------------------------------

### Total Employment as of Feb 2022

```{r}
data$fred$employ <- 
  get_fredr_series(
    c("PORT941NA", "AUST448NA", "INDI918NA"),
    "data_fred_employ", params)

valueBox(
    format_number(
      get_fred_latest_value(data$fred$employ) , accuracy = 1L))
```

### Year-over-Year Change

```{r}
yoy <- get_fred_yoy(data$fred$employ)

valueBox(scales::percent(yoy, accuracy = 0.1),
         color = case_when(yoy > .01 ~ "success",
                           yoy < -.01 ~ "danger",
                           TRUE ~ "warning"))
```

Row
-------------------------------------

### History

```{r}
make_plot(data$fred$employ, group = "series_id")
```

Row {data-height=75}
-------------------------------------

```{r}
h3("Unemployment Rate, Portland MSA")
```

Row
-------------------------------------

### Unemployment as of Feb 2022

```{r}
data$fred$unemploy <- 
  get_fredr_series(
    c("PORT941URN", "AUST448URN", "INDI918URN"),
    "data_fred_unemploy", params)

valueBox(
    format_number(
      get_fred_latest_value(data$fred$unemploy), accuracy = 0.1))
```

### Year-over-Year Change

```{r}
yoy <- get_fred_yoy(data$fred$unemploy)

valueBox(scales::percent(yoy, accuracy = 0.1),
         color = case_when(yoy > .01 ~ "danger",
                           yoy < -.01 ~ "success",
                           TRUE ~ "warning"))
```

Row
-------------------------------------

### History

```{r}
make_plot(data$fred$unemploy, group = "series_id")
```

Row {data-height=75}
-------------------------------------

```{r}
h3("Consumer Price Index, West-Size A")
```

Row
-------------------------------------

### Consumer Price Index as of Feb 2022

```{r}
data$fred$cpi <- get_fredr_series("CUURA400SA0", "data_fred_cpi", params)

valueBox(
    format_number(
      get_fred_latest_value(data$fred$cpi), accuracy = 1L))
```

### Year-over-Year Change

```{r}
yoy <- get_fred_yoy(data$fred$cpi)

valueBox(scales::percent(yoy, accuracy = 0.1),
         color = case_when(yoy > .01 ~ "success",
                           yoy < -.01 ~ "danger",
                           TRUE ~ "warning"))
```

Row
-------------------------------------

### History

```{r}
make_plot(data$fred$cpi)
```