Real Estate
===================================== 


Row {data-height=75}
-------------------------------------

```{r}
h3("S&P/Case-Shiller OR-Portland Home Price Index")
```

Row
-------------------------------------

### Home Price Index as of Jan 2022

```{r}
data$fred$home_price <- get_fredr_series("POXRSA", "data_fred_home_price", params)

valueBox(
    format_number(
      get_fred_latest_value(data$fred$home_price), accuracy = 1L))
```

### Year-over-Year Change

```{r}
yoy <- get_fred_yoy(data$fred$home_price)

valueBox(scales::percent(yoy, accuracy = 0.1),
         color = case_when(yoy > .01 ~ "danger",
                           yoy < -.01 ~ "success",
                           TRUE ~ "warning"))
```

Row
-------------------------------------

### History

```{r}
make_plot(data$fred$home_price)
```


Row
-------------------------------------
### Portland Metro Industrial Vacancy Rate

Row
-------------------------------------
### Portland Office Vacancy Rate

Row
-------------------------------------
### Multnomah County Multi-Family Vacancy Rate