Commerce
=====================================  

Row {data-height=75}
-------------------------------------

```{r}
h3("Total Air Passengers")
```

Row
-------------------------------------

### Total Year-to-Date Air Passengers as of `r paste(month(params$end_date, label = TRUE), year(params$end_date))`

```{r air_passengers_month}
ytd_current <- get_ytd(
  data$port$passenger_historical, "current", "Month", "Passengers", params)

valueBox(
    format_number(ytd_current, accuracy = 1L),
    icon = "fa-plane")
```

### Year-over-Year Change

```{r air_passengers_yoy}

ytd_last <- get_ytd(
  data$port$passenger_historical, "last", "Month", "Passengers", params)

yoy <- (ytd_current - ytd_last) / ytd_last

valueBox(scales::percent(
  yoy, accuracy = 0.1),
         color = case_when(yoy > .01 ~ "success",
                           yoy < -.01 ~ "danger",
                           TRUE ~ "warning"))
```

Row {data-height=350}
-------------------------------------

### History

```{r air_passengers_history}
data$port$passenger_historical %>%
  mutate(Month = as.Date(Month)) %>%
make_plot(x = "Month", y = "Passengers")
```

Row {data-height=75}
-------------------------------------

```{r}
h3("Total Air Freight")
```

Row
-------------------------------------
### Total Year-to-Date Tons of Air Freight as of `r paste(month(params$end_date, label = TRUE), year(params$end_date))`

```{r air_freight_month}
ytd_current <- get_ytd(
  data$port$freight_historical, "current", "Month", "Freight", params)

valueBox(
    format_number(ytd_current, accuracy = 1L),
    icon = "fa-plane")
```

### Year-over-Year Change

```{r air_freight_yoy}

ytd_last <- get_ytd(
  data$port$freight_historical, "last", "Month", "Freight", params)

yoy <- (ytd_current - ytd_last) / ytd_last

valueBox(scales::percent(
  yoy, accuracy = 0.1),
         color = case_when(yoy > .01 ~ "success",
                           yoy < -.01 ~ "danger",
                           TRUE ~ "warning"))
```

Row {data-height=350}
-------------------------------------

### History

```{r air_freight_history}
data$port$freight_historical %>%
  mutate(Month = as.Date(Month)) %>%
make_plot(x = "Month", y = "Freight")
```

Row {data-height=75}
-------------------------------------

```{r}
h3("Total Marine Freight")
```

Row
-------------------------------------

### Total Tonnage as of Mar 2022 (YTD)
```{r}
valueBox(
  format_number(tail(data$port$marine$`Total Tonnage`, n=1) , accuracy = 1L), 
  icon = "fa-dolly")
```

Row {data-height=350}
-------------------------------------
### History

```{r}
  ggplotly(
    data$port$marine %>%
      ggplot(aes(x = Date, y = `Total Tonnage`)) +
      geom_line() +
      scale_y_continuous(labels = comma) +
      scale_x_date(date_breaks = "3 months" , date_labels = "%b %Y") +
      scale_color_viridis(discrete = TRUE) +
      theme_minimal() +
      theme(axis.text.x = element_text(angle = 45),
            axis.title.x = element_blank()))
```

### Context

We will explain this here